### ISSUE TITLE
Crash if run from the Program Files directory

### ISSUE THREAD

**Issue by pmachapman** [pmachapman/GoTo.Bible#46]
The following crash occurs if the program is run form the program files directory. We should have WebView2 create its user data folder in AppData\Local (see also https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder).
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************* Exception Text *************
System.Runtime.InteropServices.COMException (0x800700AA): The requested resource is in use. (0x800700AA)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2ControllerAsync(IntPtr ParentWindow)
   at Microsoft.Web.WebView2.WinForms.WebView2.InitCoreWebView2Async(CoreWebView2Environment environment)
   at GoToBible.Windows.FormMain.InitialiseAsync() in D:\source\repos\GoTo.Bible\GoToBible.Windows\FormMain.cs:line 346
   at GoToBible.Windows.FormMain.FormMain_Load(Object sender, EventArgs e) in D:\source\repos\GoTo.Bible\GoToBible.Windows\FormMain.cs:line 262
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)


************* Loaded Assemblies *************
System.Private.CoreLib
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Private.CoreLib.dll
----------------------------------------
GoToBible.Windows
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Program%20Files/GoTobible/GoToBible.Windows.dll
----------------------------------------
System.Runtime
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 5.0.8.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 5.0.8.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Collections.Specialized.dll
----------------------------------------
System.Collections
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Collections.dll
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.902.49
    Win32 Version: 1.0.902.49
    CodeBase: file:///E:/Program%20Files/GoTobible/Microsoft.Web.WebView2.Core.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/mscorlib.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Diagnostics.Process.dll
----------------------------------------
System.Threading
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Diagnostics.TraceSource.dll
----------------------------------------
GoToBible.Model
    Assembly Version: 1.1.1.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///E:/Program%20Files/GoTobible/GoToBible.Model.dll
----------------------------------------
Microsoft.Extensions.Caching.Memory
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///E:/Program%20Files/GoTobible/Microsoft.Extensions.Caching.Memory.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/netstandard.dll
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///E:/Program%20Files/GoTobible/Microsoft.Extensions.Options.dll
----------------------------------------
Microsoft.Extensions.Caching.Abstractions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///E:/Program%20Files/GoTobible/Microsoft.Extensions.Caching.Abstractions.dll
----------------------------------------
GoToBible.Engine
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Program%20Files/GoTobible/GoToBible.Engine.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 5.0.0.2
    Win32 Version: 5.0.421.11614
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Drawing.Common.dll
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///E:/Program%20Files/GoTobible/Microsoft.Extensions.Logging.Abstractions.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Collections.Concurrent.dll
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///E:/Program%20Files/GoTobible/Microsoft.Extensions.Primitives.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.ComponentModel.TypeConverter.dll
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.902.49
    Win32 Version: 1.0.902.49
    CodeBase: file:///E:/Program%20Files/GoTobible/Microsoft.Web.WebView2.WinForms.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///E:/Program%20Files/GoTobible/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Runtime.Extensions.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.ComponentModel.dll
----------------------------------------
System.Memory
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Memory.dll
----------------------------------------
System.Drawing
    Assembly Version: 5.0.8.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Drawing.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Resources.Extensions.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.ObjectModel.dll
----------------------------------------
System.Linq
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Linq.dll
----------------------------------------
System.Buffers
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Buffers.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Private.Uri.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Collections.NonGeneric.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Private.Xml.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Text.RegularExpressions.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.IO.FileSystem.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Net.WebClient.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Text.Encoding.Extensions.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Xml.XmlSerializer.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Threading.Tasks.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Web.HttpUtility
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Web.HttpUtility.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Threading.ThreadPool.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.Collections.Immutable.dll
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.821.31504
    CodeBase: file:///E:/Program%20Files/GoTobible/System.IO.MemoryMappedFiles.dll
----------------------------------------

************* JIT Debugging *************
```

**Comment by pmachapman** [comment]
Fixed in commit 5f416ebb84898f661454c37c602a758988c035cc
